name= input("Enter your name: ")
age= input("Enter your age: ")
gender= input("Enter your gender: ")
grade= input("Enter your grade: ")
is_student= input("Are you a student? (True/False): ")
weight= input("Enter your weight: ")
height= input("Enter your height: ")

print("My name is :", name)
print("My age is :", age)
print("My gender is :", gender)
print("My grade is :", grade)
print("I am a student :", is_student)
print("My weight is :", weight)
print("My height is:", height)
